'use client';
import { FirebaseOptions } from 'firebase/app';

// This configuration is automatically generated by Firebase Studio.
// Manual edits may be overwritten.
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyCn7Amvw9sN5HrGwNLJNkLSAxn7GcV5Ey8",
  authDomain: "gestaodefrequencia.firebaseapp.com",
  projectId: "gestaodefrequencia",
  storageBucket: "gestaodefrequencia.appspot.com",
  messagingSenderId: "648424463640",
  appId: "1:648424463640:web:a1719abea055592c35126d"
};
