'use client';
import { FirebaseOptions } from 'firebase/app';

// This configuration is automatically generated by Firebase Studio.
// Manual edits may be overwritten.
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyDxuctOm-Cup-hxD45Cng7DqL20ex8zYpA",
  authDomain: "gestaodefrequencia.firebaseapp.com",
  projectId: "gestaodefrequencia",
  storageBucket: "gestaodefrequencia.appspot.com",
  messagingSenderId: "485562194451",
  appId: "1:485562194451:web:a1719abea055592c35126d"
};
